/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ResizerRouteImport } from './routes/resizer'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComicsSlugRouteImport } from './routes/comics.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedCartRouteImport } from './routes/_authenticated/cart'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/_admin/route'
import { Route as AuthenticatedCheckoutIndexRouteImport } from './routes/_authenticated/checkout/index'
import { Route as ApiPublicBootstrapAdminRouteImport } from './routes/api/public/bootstrap-admin'
import { Route as AuthenticatedReaderSlugRouteImport } from './routes/_authenticated/reader.$slug'
import { Route as AuthenticatedCheckoutSuccessRouteImport } from './routes/_authenticated/checkout/success'
import { Route as AuthenticatedAdminAdminIndexRouteImport } from './routes/_authenticated/_admin/admin.index'
import { Route as AuthenticatedAdminAdminSoundtracksRouteImport } from './routes/_authenticated/_admin/admin.soundtracks'
import { Route as AuthenticatedAdminAdminPublishersRouteImport } from './routes/_authenticated/_admin/admin.publishers'
import { Route as AuthenticatedAdminAdminNewRouteImport } from './routes/_authenticated/_admin/admin.new'
import { Route as AuthenticatedAdminAdminComicIdRouteImport } from './routes/_authenticated/_admin/admin.$comicId'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ResizerRoute = ResizerRouteImport.update({
  id: '/resizer',
  path: '/resizer',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComicsSlugRoute = ComicsSlugRouteImport.update({
  id: '/comics/$slug',
  path: '/comics/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCartRoute = AuthenticatedCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCheckoutIndexRoute =
  AuthenticatedCheckoutIndexRouteImport.update({
    id: '/checkout/',
    path: '/checkout/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicBootstrapAdminRoute = ApiPublicBootstrapAdminRouteImport.update({
  id: '/api/public/bootstrap-admin',
  path: '/api/public/bootstrap-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReaderSlugRoute = AuthenticatedReaderSlugRouteImport.update({
  id: '/reader/$slug',
  path: '/reader/$slug',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCheckoutSuccessRoute =
  AuthenticatedCheckoutSuccessRouteImport.update({
    id: '/checkout/success',
    path: '/checkout/success',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAdminIndexRoute =
  AuthenticatedAdminAdminIndexRouteImport.update({
    id: '/admin/',
    path: '/admin/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminSoundtracksRoute =
  AuthenticatedAdminAdminSoundtracksRouteImport.update({
    id: '/admin/soundtracks',
    path: '/admin/soundtracks',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminPublishersRoute =
  AuthenticatedAdminAdminPublishersRouteImport.update({
    id: '/admin/publishers',
    path: '/admin/publishers',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminNewRoute =
  AuthenticatedAdminAdminNewRouteImport.update({
    id: '/admin/new',
    path: '/admin/new',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminComicIdRoute =
  AuthenticatedAdminAdminComicIdRouteImport.update({
    id: '/admin/$comicId',
    path: '/admin/$comicId',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/resizer': typeof ResizerRoute
  '/shop': typeof ShopRoute
  '/support': typeof SupportRoute
  '/account': typeof AuthenticatedAccountRoute
  '/cart': typeof AuthenticatedCartRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/comics/$slug': typeof ComicsSlugRoute
  '/checkout/success': typeof AuthenticatedCheckoutSuccessRoute
  '/reader/$slug': typeof AuthenticatedReaderSlugRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/checkout/': typeof AuthenticatedCheckoutIndexRoute
  '/admin/$comicId': typeof AuthenticatedAdminAdminComicIdRoute
  '/admin/new': typeof AuthenticatedAdminAdminNewRoute
  '/admin/publishers': typeof AuthenticatedAdminAdminPublishersRoute
  '/admin/soundtracks': typeof AuthenticatedAdminAdminSoundtracksRoute
  '/admin/': typeof AuthenticatedAdminAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/resizer': typeof ResizerRoute
  '/shop': typeof ShopRoute
  '/support': typeof SupportRoute
  '/account': typeof AuthenticatedAccountRoute
  '/cart': typeof AuthenticatedCartRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/comics/$slug': typeof ComicsSlugRoute
  '/checkout/success': typeof AuthenticatedCheckoutSuccessRoute
  '/reader/$slug': typeof AuthenticatedReaderSlugRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/checkout': typeof AuthenticatedCheckoutIndexRoute
  '/admin/$comicId': typeof AuthenticatedAdminAdminComicIdRoute
  '/admin/new': typeof AuthenticatedAdminAdminNewRoute
  '/admin/publishers': typeof AuthenticatedAdminAdminPublishersRoute
  '/admin/soundtracks': typeof AuthenticatedAdminAdminSoundtracksRoute
  '/admin': typeof AuthenticatedAdminAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/resizer': typeof ResizerRoute
  '/shop': typeof ShopRoute
  '/support': typeof SupportRoute
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/cart': typeof AuthenticatedCartRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/comics/$slug': typeof ComicsSlugRoute
  '/_authenticated/checkout/success': typeof AuthenticatedCheckoutSuccessRoute
  '/_authenticated/reader/$slug': typeof AuthenticatedReaderSlugRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/_authenticated/checkout/': typeof AuthenticatedCheckoutIndexRoute
  '/_authenticated/_admin/admin/$comicId': typeof AuthenticatedAdminAdminComicIdRoute
  '/_authenticated/_admin/admin/new': typeof AuthenticatedAdminAdminNewRoute
  '/_authenticated/_admin/admin/publishers': typeof AuthenticatedAdminAdminPublishersRoute
  '/_authenticated/_admin/admin/soundtracks': typeof AuthenticatedAdminAdminSoundtracksRoute
  '/_authenticated/_admin/admin/': typeof AuthenticatedAdminAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/blog'
    | '/resizer'
    | '/shop'
    | '/support'
    | '/account'
    | '/cart'
    | '/library'
    | '/blog/$slug'
    | '/comics/$slug'
    | '/checkout/success'
    | '/reader/$slug'
    | '/api/public/bootstrap-admin'
    | '/checkout/'
    | '/admin/$comicId'
    | '/admin/new'
    | '/admin/publishers'
    | '/admin/soundtracks'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/blog'
    | '/resizer'
    | '/shop'
    | '/support'
    | '/account'
    | '/cart'
    | '/library'
    | '/blog/$slug'
    | '/comics/$slug'
    | '/checkout/success'
    | '/reader/$slug'
    | '/api/public/bootstrap-admin'
    | '/checkout'
    | '/admin/$comicId'
    | '/admin/new'
    | '/admin/publishers'
    | '/admin/soundtracks'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/blog'
    | '/resizer'
    | '/shop'
    | '/support'
    | '/_authenticated/_admin'
    | '/_authenticated/account'
    | '/_authenticated/cart'
    | '/_authenticated/library'
    | '/blog/$slug'
    | '/comics/$slug'
    | '/_authenticated/checkout/success'
    | '/_authenticated/reader/$slug'
    | '/api/public/bootstrap-admin'
    | '/_authenticated/checkout/'
    | '/_authenticated/_admin/admin/$comicId'
    | '/_authenticated/_admin/admin/new'
    | '/_authenticated/_admin/admin/publishers'
    | '/_authenticated/_admin/admin/soundtracks'
    | '/_authenticated/_admin/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  ResizerRoute: typeof ResizerRoute
  ShopRoute: typeof ShopRoute
  SupportRoute: typeof SupportRoute
  ComicsSlugRoute: typeof ComicsSlugRoute
  ApiPublicBootstrapAdminRoute: typeof ApiPublicBootstrapAdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resizer': {
      id: '/resizer'
      path: '/resizer'
      fullPath: '/resizer'
      preLoaderRoute: typeof ResizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comics/$slug': {
      id: '/comics/$slug'
      path: '/comics/$slug'
      fullPath: '/comics/$slug'
      preLoaderRoute: typeof ComicsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cart': {
      id: '/_authenticated/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof AuthenticatedCartRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checkout/': {
      id: '/_authenticated/checkout/'
      path: '/checkout'
      fullPath: '/checkout/'
      preLoaderRoute: typeof AuthenticatedCheckoutIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/bootstrap-admin': {
      id: '/api/public/bootstrap-admin'
      path: '/api/public/bootstrap-admin'
      fullPath: '/api/public/bootstrap-admin'
      preLoaderRoute: typeof ApiPublicBootstrapAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reader/$slug': {
      id: '/_authenticated/reader/$slug'
      path: '/reader/$slug'
      fullPath: '/reader/$slug'
      preLoaderRoute: typeof AuthenticatedReaderSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checkout/success': {
      id: '/_authenticated/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof AuthenticatedCheckoutSuccessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_admin/admin/': {
      id: '/_authenticated/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/soundtracks': {
      id: '/_authenticated/_admin/admin/soundtracks'
      path: '/admin/soundtracks'
      fullPath: '/admin/soundtracks'
      preLoaderRoute: typeof AuthenticatedAdminAdminSoundtracksRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/publishers': {
      id: '/_authenticated/_admin/admin/publishers'
      path: '/admin/publishers'
      fullPath: '/admin/publishers'
      preLoaderRoute: typeof AuthenticatedAdminAdminPublishersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/new': {
      id: '/_authenticated/_admin/admin/new'
      path: '/admin/new'
      fullPath: '/admin/new'
      preLoaderRoute: typeof AuthenticatedAdminAdminNewRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/$comicId': {
      id: '/_authenticated/_admin/admin/$comicId'
      path: '/admin/$comicId'
      fullPath: '/admin/$comicId'
      preLoaderRoute: typeof AuthenticatedAdminAdminComicIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAdminComicIdRoute: typeof AuthenticatedAdminAdminComicIdRoute
  AuthenticatedAdminAdminNewRoute: typeof AuthenticatedAdminAdminNewRoute
  AuthenticatedAdminAdminPublishersRoute: typeof AuthenticatedAdminAdminPublishersRoute
  AuthenticatedAdminAdminSoundtracksRoute: typeof AuthenticatedAdminAdminSoundtracksRoute
  AuthenticatedAdminAdminIndexRoute: typeof AuthenticatedAdminAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAdminComicIdRoute: AuthenticatedAdminAdminComicIdRoute,
    AuthenticatedAdminAdminNewRoute: AuthenticatedAdminAdminNewRoute,
    AuthenticatedAdminAdminPublishersRoute:
      AuthenticatedAdminAdminPublishersRoute,
    AuthenticatedAdminAdminSoundtracksRoute:
      AuthenticatedAdminAdminSoundtracksRoute,
    AuthenticatedAdminAdminIndexRoute: AuthenticatedAdminAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedCartRoute: typeof AuthenticatedCartRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedCheckoutSuccessRoute: typeof AuthenticatedCheckoutSuccessRoute
  AuthenticatedReaderSlugRoute: typeof AuthenticatedReaderSlugRoute
  AuthenticatedCheckoutIndexRoute: typeof AuthenticatedCheckoutIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedCartRoute: AuthenticatedCartRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedCheckoutSuccessRoute: AuthenticatedCheckoutSuccessRoute,
  AuthenticatedReaderSlugRoute: AuthenticatedReaderSlugRoute,
  AuthenticatedCheckoutIndexRoute: AuthenticatedCheckoutIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  ResizerRoute: ResizerRoute,
  ShopRoute: ShopRoute,
  SupportRoute: SupportRoute,
  ComicsSlugRoute: ComicsSlugRoute,
  ApiPublicBootstrapAdminRoute: ApiPublicBootstrapAdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
