// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function createSupabaseAdminClient() {
  console.log('[Supabase Admin] Creating admin client...');

  const SUPABASE_URL = process.env.SUPABASE_URL;
  const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

  // Log that we have the URL (without exposing the key)
  if (SUPABASE_URL) {
    console.log(`[Supabase Admin] SUPABASE_URL is set to: ${SUPABASE_URL}`);
  } else {
    console.warn('[Supabase Admin] SUPABASE_URL is missing.');
  }

  if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_SERVICE_ROLE_KEY ? ['SUPABASE_SERVICE_ROLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase Admin] ${message}`);
    throw new Error(message);
  }

  // Optionally, you could log that the key exists (but never log the key itself)
  console.log('[Supabase Admin] Service role key is present (not logged for security).');

  // Create the client with admin privileges
  const client = createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    }
  });

  console.log('[Supabase Admin] Admin client created successfully.');
  return client;
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Import like: import { supabaseAdmin } from "@/integrations/supabase/client.server";
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) {
      console.log(`[Supabase Admin] First access to property "${String(prop)}" – initializing client now.`);
      _supabaseAdmin = createSupabaseAdminClient();
    } else {
      console.log(`[Supabase Admin] Accessing property "${String(prop)}" – client already initialized.`);
    }
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});


// Optional: warn if this module is accidentally imported on the client side
if (typeof window !== 'undefined') {
  console.warn(
    '[Supabase Admin] ⚠️ This admin client is being imported in a browser environment. ' +
    'This is a security risk. Only import and use this module in server-side code.'
  );
}