// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function createSupabaseClient() {
  console.log('[Supabase Client] Creating regular client...');

  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (SUPABASE_URL) {
    console.log(`[Supabase Client] SUPABASE_URL is set to: ${SUPABASE_URL}`);
  } else {
    console.warn('[Supabase Client] SUPABASE_URL is missing.');
  }

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase Client] ${message}`);
    throw new Error(message);
  }

  // Log that the anon key exists (without exposing it)
  console.log('[Supabase Client] Publishable (anon) key is present (not logged for security).');

  const isBrowser = typeof window !== 'undefined';
  console.log(`[Supabase Client] Running in: ${isBrowser ? 'Browser' : 'Server'} environment.`);

  const client = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: isBrowser ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });

  console.log('[Supabase Client] Regular client created successfully.');
  return client;
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) {
      console.log(`[Supabase Client] First access to property "${String(prop)}" – initializing client now.`);
      _supabase = createSupabaseClient();
    } else {
      console.log(`[Supabase Client] Accessing property "${String(prop)}" – client already initialized.`);
    }
    return Reflect.get(_supabase, prop, receiver);
  },
});